"""usage_events: confidence e no_speech do STT, registrados em todo turn

Revision ID: 472d4f6cb79c
Revises: c5e2a71b93d4
Create Date: 2026-09-13 03:02:16.049588

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "472d4f6cb79c"
down_revision: str | Sequence[str] | None = "c5e2a71b93d4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Adiciona nullable, faz o backfill das linhas existentes, então trava NOT NULL.

    Ajustado à mão (o autogenerate não sabe disto): `0.0` para as linhas
    anteriores a este card não é uma medição real de confidence/no_speech —
    é "não medido", declarado como tal para quem consultar o histórico. Toda
    linha NOVA, a partir daqui, grava o valor real (CARD-040).
    """
    op.add_column(
        "usage_events", sa.Column("stt_confidence", sa.Float(), nullable=True)
    )
    op.add_column("usage_events", sa.Column("stt_no_speech", sa.Float(), nullable=True))
    op.execute(
        "UPDATE usage_events SET stt_confidence = 0.0, stt_no_speech = 0.0 "
        "WHERE stt_confidence IS NULL"
    )
    op.alter_column("usage_events", "stt_confidence", nullable=False)
    op.alter_column("usage_events", "stt_no_speech", nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("usage_events", "stt_no_speech")
    op.drop_column("usage_events", "stt_confidence")
    # ### end Alembic commands ###
