/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness — o processo responde */
        get: operations["liveness_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness — as dependências de infraestrutura respondem
         * @description 200 apenas se as três dependências responderem; 503 caso contrário.
         *
         *     O corpo é o mesmo nos dois casos — quem depura precisa saber *qual* caiu, e
         *     isso não deve depender de o endpoint ter respondido 200.
         */
        get: operations["readiness_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * As sessões do aluno, da mais recente para a mais antiga
         * @description Leitura pura: não gasta cota e responde `200` mesmo com a cota estourada.
         *
         *     Aluno sem sessão nenhuma recebe `sessions: []` (RF5) — ausência de sessões
         *     é uma resposta, não um recurso que não existe.
         */
        get: operations["listar_sessoes_v1_sessions_get"];
        put?: never;
        /** Abre uma sessão de conversa */
        post: operations["criar_sessao_v1_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{session_id}/end": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Encerra a sessão e devolve o resumo pós-sessão
         * @description Idempotente (RF2): chamar de novo numa sessão já encerrada devolve o
         *     mesmo resumo, não um erro — ver o docstring de ``EndSessionHandler``.
         */
        post: operations["encerrar_sessao_v1_sessions__session_id__end_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/students/me/quota": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * O saldo de cota e o estado do serviço, como leitura
         * @description Nunca recusa (RNF1): kill switch ativo ou cota estourada respondem
         *     `200` — é a tela que EXPLICA a parede, e ela não pode estar atrás dela.
         */
        get: operations["ler_cota_v1_students_me_quota_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{session_id}/turns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Envia a fala do aluno e enfileira o turno
         * @description ``202`` com o ``turn_id``. O trabalho começa depois da resposta.
         *
         *     O cabeçalho é **obrigatório** de propósito. Torná-lo opcional ("se faltar, eu
         *     gero uma") faria o esquecimento do cliente virar um turno extra processado e
         *     pago, em silêncio — e a rede móvel, que é o caso de uso inteiro da
         *     idempotência, é justamente onde o reenvio acontece.
         *
         *     O rate limit (ADR-0063) roda como dependência da ROTA, antes até deste
         *     corpo começar — é o que faz a checagem custar zero IO de upload quando
         *     nega. A cota diária e o kill switch, ao contrário, precisam do
         *     ``student_id`` (só a sessão o revela) e por isso moram dentro do
         *     ``handler.handle``.
         */
        post: operations["criar_turn_v1_sessions__session_id__turns_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/turns/{turn_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * O turno completo — o contrato de recuo (ADR-0026, item 4)
         * @description Tudo que o app precisa mostrar, com as URLs já assinadas.
         *
         *     Assinar N trechos são N HMACs locais (microssegundos cada, ADR-0024) — é o
         *     que torna aceitável entregar as URLs prontas em vez de o cliente pedir uma
         *     por trecho, que era o roundtrip por frase que o ADR-0024 recusou.
         */
        get: operations["obter_turn_v1_turns__turn_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/turns/{turn_id}/discard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 'Descartar': o turn some da tela ativa, sem apagar nada (CARD-032)
         * @description Idempotente (RNF1): descartar duas vezes é o mesmo que uma, `204` as duas.
         *
         *     Nada é apagado (RF1/RF4) — o turn continua no histórico e nas agregações
         *     (RNF4/RNF5). O único efeito é ``discarded_at`` marcado, para o cliente
         *     parar de mostrá-lo como turn ativo.
         */
        post: operations["descartar_turn_v1_turns__turn_id__discard_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/turns/{turn_id}/translations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Traduz para português um texto do turno (CARD-036)
         * @description O aluno pediu a tradução de um texto que o produto já produziu.
         *
         *     **O corpo diz QUAL texto, nunca o texto** (RF1). Traduzir de novo o mesmo
         *     texto não cobra de novo (RF4) e responde `cached: true`.
         */
        post: operations["traduzir_texto_do_turn_v1_turns__turn_id__translations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/turns/{turn_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Entrega progressiva por SSE (ADR-0026)
         * @description O stream. Fecha em ``completed``/``failed``, no prazo, ou no disconnect.
         *
         *     **Quem fecha no disconnect é o `sse-starlette`**, e é o principal motivo de a
         *     biblioteca existir aqui: ele observa a mensagem ASGI ``http.disconnect`` e
         *     **cancela a corrotina** deste gerador. O cancelamento propaga para o
         *     ``async with`` da assinatura dentro do caso de uso, que desfaz o
         *     ``SUBSCRIBE`` e devolve a conexão do Redis. Sem isso, um aluno que fecha o
         *     app deixaria uma conexão pendurada até o prazo de 60 s — multiplicado por
         *     todo mundo.
         *
         *     O `Last-Event-ID` chega por cabeçalho porque é assim que o `EventSource`
         *     nativo reconecta: ele o manda sozinho, sem o cliente escrever uma linha.
         */
        get: operations["acompanhar_turn_v1_turns__turn_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BlockedReason
         * @description Por que o aluno não pode falar AGORA — nunca por quê em dólares (RF4).
         *
         *     ``DAILY_MINUTES`` é o caso comum, e a tela já tem a barra para ele. Os
         *     outros dois são os que RF3/RF5 pedem para não caírem na mesma mensagem:
         *     ``MANY_SHORT_TURNS`` é o teto de turns mordendo com minutos sobrando, e
         *     ``SERVICE_PAUSED`` é o kill switch — um fato do PRODUTO, não do aluno.
         * @enum {string}
         */
        BlockedReason: "daily_minutes" | "many_short_turns" | "service_paused";
        /** Body_criar_turn_v1_sessions__session_id__turns_post */
        Body_criar_turn_v1_sessions__session_id__turns_post: {
            /**
             * Audio
             * @description A fala do aluno.
             */
            audio: string;
        };
        /**
         * ChunkPayload
         * @description Um trecho tocável da resposta — no GET e no evento ``chunk``.
         *
         *     ``url`` é uma URL **pré-assinada e de vida curta** (ADR-0024): ela é montada
         *     no momento da entrega, com TTL de ``media_url_ttl``. Não é endereço estável e
         *     não deve ser guardada pelo cliente além do playback do turn.
         */
        ChunkPayload: {
            /**
             * Index
             * @description 0-based e denso; é a ordem de playback.
             */
            index: number;
            /**
             * Url
             * @description URL assinada, válida por media_url_ttl.
             */
            url: string;
            /** Duration Seconds */
            duration_seconds: number;
            /**
             * Text
             * @description A frase que gerou este trecho.
             */
            text: string;
        };
        /**
         * CompletedPayload
         * @description Evento ``completed``. Carrega a URL do áudio inteiro, já assinada.
         */
        CompletedPayload: {
            /** Reply Audio Url */
            reply_audio_url: string;
        };
        /**
         * CorrectionPayload
         * @description Uma correção tipada — no ``GET`` e no evento ``feedback``.
         *
         *     Mesma garantia do ``ChunkPayload`` e pela mesma razão (ADR-0026): o payload
         *     do evento e o do ``GET`` descrevem a mesma coisa, então **saem do mesmo
         *     schema** ou divergem no primeiro campo que alguém acrescentar a um só.
         *
         *     ``index`` viaja porque ele não é detalhe de armazenamento: é a **ordem
         *     pedagógica**, e é o contrato que diz ao cliente qual correção destacar
         *     quando só couber uma na tela (CARD-016).
         */
        CorrectionPayload: {
            /**
             * Index
             * @description 0-based e denso; é a ordem pedagógica.
             */
            index: number;
            type: components["schemas"]["CorrectionType"];
            /**
             * Original Excerpt
             * @description Trecho verbatim da fala do aluno.
             */
            original_excerpt: string;
            /** Corrected Form */
            corrected_form: string;
            /** Explanation */
            explanation: string;
            /** @description Escala fechada. O rótulo em pt-BR é do cliente, não daqui. */
            severity: components["schemas"]["Severity"];
        };
        /**
         * CorrectionType
         * @description A natureza do erro. Enum **fechado**, como ``TurnStatus``.
         *
         *     Acrescentar um valor é aditivo e permitido; renomear não é (ADR-0008), e a
         *     consequência de renomear é dupla — quebra o cliente antigo **e** invalida
         *     todo valor já gravado na coluna, porque o Postgres guarda o texto do membro.
         *
         *     ``OTHER`` existe para que o modelo tenha para onde ir quando a correção não
         *     couber nas outras quatro. Sem essa saída, o custo de uma classificação
         *     impossível seria uma resposta fora do schema — ou seja, ``LlmError`` e turn
         *     falho por um erro de taxonomia.
         * @enum {string}
         */
        CorrectionType: "grammar" | "vocabulary" | "preposition" | "word_order" | "other";
        /**
         * DependencyCheck
         * @description Estado de uma dependência de infraestrutura.
         */
        DependencyCheck: {
            /**
             * Status
             * @enum {string}
             */
            status: "up" | "down";
            /** Latency Ms */
            latency_ms: number;
            /** Error */
            error?: string | null;
        };
        /**
         * FailedPayload
         * @description Evento ``failed`` — inclusive depois de entrega parcial (ADR-0023).
         */
        FailedPayload: {
            /** Reason */
            reason: string;
            /** Delivered Partially */
            delivered_partially: boolean;
        };
        /**
         * FeedbackPayload
         * @description Evento ``feedback`` — agora reconstruído na retomada (CARD-013).
         *
         *     Era **o único evento que a retomada não reconstruía**, porque correção não
         *     era persistida (ADR-0035, ADR-0041 item 5). Com ``turn.corrections`` no
         *     banco, o gatilho que aquele ADR deixou escrito disparou e ele volta como
         *     qualquer outro.
         *
         *     **Os quatro campos velhos continuam aqui, e continuam obrigatórios**
         *     (ADR-0008: proibido remover ou renomear dentro de ``/v1`` — a restrição dura
         *     é o app na loja que não atualiza quando queremos). O que mudou é de onde
         *     saem: eles são **derivados** de ``corrections`` por ``legacy_summary``, e não
         *     mais gerados pelo modelo. Quando morrem: no ``/v2``, ou antes, quando o app
         *     mínimo suportado já ler ``corrections[]``.
         */
        FeedbackPayload: {
            /**
             * Has Mistakes
             * @description LEGADO — derivado de corrections.
             */
            has_mistakes: boolean;
            /**
             * Original
             * @description LEGADO — corrections[0].original_excerpt.
             */
            original: string;
            /**
             * Corrected
             * @description LEGADO — corrections[0].corrected_form.
             */
            corrected: string;
            /**
             * Tip
             * @description LEGADO — corrections[0].explanation.
             */
            tip: string;
            /**
             * Corrections
             * @description Correções tipadas (CARD-013). Campo ADITIVO.
             */
            corrections?: components["schemas"]["CorrectionPayload"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LivenessResponse
         * @description Resposta de ``GET /health``.
         */
        LivenessResponse: {
            /**
             * Status
             * @default alive
             * @constant
             */
            status: "alive";
        };
        /** QuotaStatusResponse */
        QuotaStatusResponse: {
            /**
             * Spoken Seconds
             * @description Falado hoje, na janela da cota.
             */
            spoken_seconds: number;
            /**
             * Quota Spoken Seconds
             * @description O teto comunicado ao aluno.
             */
            quota_spoken_seconds: number;
            /**
             * Resets At
             * Format: date-time
             * @description Instante absoluto da virada — o MESMO do `retry_after` do 429 de cota (mesma fonte, ADR-0063).
             */
            resets_at: string;
            /**
             * Service Available
             * @description `false` quando o kill switch do orçamento está ativo.
             */
            service_available: boolean;
            /** @description Por que o aluno não pode falar agora, sem expor mecânica de custo. `null` quando ele pode. */
            blocked_reason?: components["schemas"]["BlockedReason"] | null;
        };
        /**
         * ReadinessResponse
         * @description Resposta de ``GET /health/ready``.
         *
         *     ``status`` é redundante em relação a ``checks`` de propósito: quem faz
         *     probe lê só o código HTTP, quem depura lê o mapa inteiro.
         */
        ReadinessResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "not_ready";
            /** Checks */
            checks?: {
                [key: string]: components["schemas"]["DependencyCheck"];
            };
        };
        /**
         * RejectedPayload
         * @description Evento ``rejected`` (ADR-0057, CARD-040) — o turn terminou sem professor.
         */
        RejectedPayload: {
            reason: components["schemas"]["RejectionReason"];
        };
        /**
         * RejectionReason
         * @description Por que um turn terminou sem resposta (ADR-0057, CARD-040).
         *
         *     Três valores, não um só: "não ouvi nada", "você não falou inglês" e "não
         *     entendi o que você disse" são três mensagens diferentes ao aluno, mesmo
         *     os três encerrando o turn do mesmo jeito (sem chamar o professor).
         *
         *     ``NOT_ENGLISH`` chegou depois dos outros dois, numa decisão de produto
         *     revisada na própria sessão do CARD-040: o STT com o idioma FIXO em inglês
         *     "traduz" silenciosamente uma fala inteira em português com confiança
         *     ALTA (medido: -0,33, quase idêntico a uma fala boa) — só a detecção real
         *     de idioma revela que o aluno não falou inglês, e é por isso que a
         *     detecção permanece ligada (ADR-0055) mesmo depois deste card.
         * @enum {string}
         */
        RejectionReason: "no_speech" | "not_english" | "low_confidence";
        /**
         * SessionListEntry
         * @description Uma sessão na listagem do histórico.
         */
        SessionListEntry: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /**
             * Ended At
             * @description Nulo significa em andamento (ADR-0016).
             */
            ended_at?: string | null;
            /**
             * Spoken Seconds
             * @description Soma de audio_duration dos turns — a MESMA definição do resumo pós-sessão (CARD-031). Uma definição, um lugar.
             */
            spoken_seconds: number;
            /** Turns */
            turns: number;
            /** Corrections */
            corrections: number;
            /**
             * Reply Media Available
             * @description `false` significa **não conte com o áudio** — é uma previsão conservadora sobre a retenção vigente (ADR-0024), não uma leitura do bucket. Nunca calcule isto no cliente pela data: a política é configuração e muda sem avisar o app.
             */
            reply_media_available: boolean;
        };
        /**
         * SessionListResponse
         * @description ``GET /v1/sessions`` — envelope, e não uma lista nua.
         *
         *     Uma lista JSON no topo da resposta é contrato que não cresce: acrescentar
         *     "quantas ficaram fora da janela" ou paginação depois exigiria mudar o tipo
         *     raiz, que é justamente o que o ADR-0008 proíbe dentro de `/v1`. O envelope
         *     custa uma linha hoje e mantém a evolução aditiva possível.
         */
        SessionListResponse: {
            /** Sessions */
            sessions: components["schemas"]["SessionListEntry"][];
            /**
             * Window Days
             * @description A janela efetivamente aplicada — o cliente não precisa lembrar o default que pediu.
             */
            window_days: number;
        };
        /**
         * SessionResponse
         * @description ``POST /v1/sessions`` — o mínimo para o cliente ter onde falar.
         */
        SessionResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Student Id
             * Format: uuid
             */
            student_id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Is Active */
            is_active: boolean;
        };
        /**
         * SessionSummaryResponse
         * @description ``POST /v1/sessions/{id}/end`` — o resumo pós-sessão (CARD-031).
         */
        SessionSummaryResponse: {
            /**
             * Spoken Seconds
             * @description Soma de audio_duration dos turns.
             */
            spoken_seconds: number;
            /** Turns */
            turns: number;
            /**
             * Corrections By Type
             * @description Só os tipos que ocorreram; vazio é 'nenhuma correção'.
             */
            corrections_by_type: {
                [key: string]: number;
            };
        };
        /**
         * Severity
         * @description Quanto o erro pesa. Três níveis, e o número é a decisão.
         *
         *     A UI apresenta severidade em **palavras** ("pequeno ajuste", "vale revisar")
         *     — o que só é traduzível a partir de uma escala pequena e estável. Três é o
         *     menor número que ainda permite ordenar e destacar sem virar escala falsa;
         *     dois perderiam o meio-termo, e um quarto nível ("critical") seria um rótulo
         *     que nem o modelo nem o produto sabem definir num tutor de conversa, ainda
         *     mais sem eval (Fase 4).
         *
         *     **O rótulo em pt-BR não mora aqui.** Tradução é apresentação e vive no
         *     cliente (CARD-016): o dia em que a mesma correção precisar aparecer em duas
         *     línguas, o domínio não muda.
         * @enum {string}
         */
        Severity: "minor" | "moderate" | "major";
        /**
         * TranscribedPayload
         * @description Evento ``transcribed``.
         */
        TranscribedPayload: {
            /** Transcript */
            transcript: string;
        };
        /**
         * TranslationRequest
         * @description Qual texto do turn traduzir.
         */
        TranslationRequest: {
            /** @description `reply` é a resposta do professor; `correction` é a explicação de uma correção. */
            target: components["schemas"]["TranslationTarget"];
            /**
             * Index
             * @description Ignorado para `reply` (há uma resposta por turn); para `correction`, é o índice 0-based na lista de correções do turn.
             * @default 0
             */
            index: number;
        };
        /**
         * TranslationResponse
         * @description O texto em português.
         */
        TranslationResponse: {
            /** Text */
            text: string;
            /**
             * Cached
             * @description `true` quando a tradução já existia e nada foi cobrado. O corpo é o mesmo nos dois casos — o campo torna o 'não paga duas vezes' observável de fora.
             */
            cached: boolean;
        };
        /**
         * TranslationTarget
         * @description Qual texto **do produto** foi traduzido (RF1).
         *
         *     Enum fechado, e é ele que implementa a decisão de segurança do RF1: o
         *     cliente escolhe entre alvos conhecidos, nunca manda o texto. Um endpoint
         *     que traduzisse texto livre seria um proxy de LLM aberto pago por nós — o
         *     risco que o card nomeia primeiro.
         *
         *     Acrescentar membro é aditivo e permitido (ADR-0008); renomear invalida
         *     linha gravada, como em todo enum persistido deste projeto (ADR-0049).
         * @enum {string}
         */
        TranslationTarget: "reply" | "correction";
        /**
         * TurnAcceptedResponse
         * @description ``202`` do ``POST`` — o turn está aceito e a caminho.
         */
        TurnAcceptedResponse: {
            /**
             * Turn Id
             * Format: uuid
             */
            turn_id: string;
            /**
             * Replayed
             * @description true quando a Idempotency-Key já tinha sido usada: nenhum turn novo foi criado e nada é reprocessado.
             */
            replayed: boolean;
        };
        /**
         * TurnEventPayloads
         * @description **Não é resposta de rota nenhuma.** Existe para o OpenAPI enxergar o SSE.
         *
         *     O ADR-0008 promete que mudança de contrato quebra o cliente **em build**. Essa
         *     promessa era **falsa para quatro dos cinco eventos**: a rota do stream devolve
         *     ``EventSourceResponse``, que não é modelo pydantic, então os payloads nunca
         *     chegavam ao OpenAPI — e portanto nunca chegavam aos tipos gerados. Só
         *     ``ChunkPayload`` escapava, por carona em ``TurnResponse.chunks``.
         *
         *     Descoberto no CARD-012, ao escrever o primeiro consumidor. Este envelope é a
         *     correção mínima: declarado no ``responses`` da rota, ele arrasta os seis para
         *     ``components.schemas``. Um campo renomeado em qualquer evento passa a virar
         *     ``error TS2339`` no app, que é o ponto inteiro do ADR-0008.
         *
         *     Os nomes dos campos são os seis nomes de evento do ADR-0026/CARD-040 — de
         *     propósito: quem ler o tipo gerado descobre o mapa ``event: → payload`` sem
         *     sair dele.
         */
        TurnEventPayloads: {
            transcribed: components["schemas"]["TranscribedPayload"];
            chunk: components["schemas"]["ChunkPayload"];
            feedback: components["schemas"]["FeedbackPayload"];
            completed: components["schemas"]["CompletedPayload"];
            rejected: components["schemas"]["RejectedPayload"];
            failed: components["schemas"]["FailedPayload"];
        };
        /**
         * TurnResponse
         * @description ``GET /v1/turns/{id}`` — completo e verdadeiro (ADR-0026, item 4).
         *
         *     Este é o **contrato de recuo**: um cliente que nunca abra o stream tem de
         *     conseguir levar um turn até o fim só com esta rota. É por isso que ela
         *     devolve tudo, e não um resumo.
         */
        TurnResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /** @description Estado grosso; não cresce (ADR-0008). */
            status: components["schemas"]["TurnStatus"];
            /** @description Etapa exibida, DERIVADA (ADR-0023/0028). */
            stage: components["schemas"]["TurnStage"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Transcript */
            transcript?: string | null;
            /** Reply Text */
            reply_text?: string | null;
            /**
             * Reply Audio Url
             * @description Áudio inteiro concatenado, assinado. Nulo antes de completar — ou depois de a retenção expirar (ADR-0024).
             */
            reply_audio_url?: string | null;
            /**
             * Delivered Partially
             * @description Falhou DEPOIS de o aluno já ter ouvido algo (ADR-0023).
             */
            delivered_partially: boolean;
            /** Failure Reason */
            failure_reason?: string | null;
            /** @description Não nulo quando o turn terminou sem chamar o professor (ADR-0057). Campo ADITIVO (ADR-0008). */
            rejection_reason?: components["schemas"]["RejectionReason"] | null;
            /**
             * Chunks
             * @description Campo ADITIVO (ADR-0008).
             */
            chunks?: components["schemas"]["ChunkPayload"][];
            /**
             * Corrections
             * @description Correções tipadas e persistidas (CARD-013). Campo ADITIVO.
             */
            corrections?: components["schemas"]["CorrectionPayload"][];
            /**
             * Discarded At
             * @description O aluno pediu 'Descartar' (CARD-032). NÃO significa apagado — o turn continua aqui inteiro; é o cliente quem decide não mostrá-lo na tela ativa. Campo ADITIVO.
             */
            discarded_at?: string | null;
        };
        /**
         * TurnStage
         * @description Etapa exibida ao aluno — **derivada**, nunca persistida (ADR-0023).
         *
         *     O vocabulário é o mesmo do ADR-0016; o que mudou foi a ordem em que os
         *     artefatos aparecem. ``queued`` não está aqui de propósito: nenhuma tela
         *     distingue "na fila" de "transcrevendo", e expor isso vazaria mecânica de
         *     infraestrutura no contrato.
         *
         *     ``NOT_UNDERSTOOD`` chegou no CARD-040 (ADR-0057): um turn pode terminar
         *     sem resposta do professor, por decisão de produto — "não deduzir" custa
         *     mais barato que responder errado. É um valor NOVO na enum, o que a
         *     própria enum permite por ser derivada (ADR-0028) — ao contrário de
         *     ``TurnStatus``, que não pode crescer.
         * @enum {string}
         */
        TurnStage: "transcribing" | "thinking" | "speaking" | "completed" | "not_understood";
        /**
         * TurnStatus
         * @description Estado de execução do Turn (ADR-0023).
         *
         *     ``StrEnum`` (Python 3.11+) é uma enum cujos membros **são** strings: o valor
         *     vai para o banco e para o JSON sem conversão manual, e ainda assim o mypy
         *     cobra o tipo. Em C# você precisaria de um conversor ou de um
         *     ``[JsonStringEnumConverter]`` para o mesmo efeito.
         *
         *     A enum **não ganha valor** com a cascata, e isso é deliberado: acrescentar
         *     ``speaking`` aqui quebraria o contrato aditivo do ADR-0008 (cliente antigo
         *     que trate os casos de forma exaustiva) e recriaria a duplicação que o
         *     ADR-0016 rejeitou. A granularidade fina vive em ``TurnStage``, que é
         *     derivado e por isso pode crescer sem migration.
         * @enum {string}
         */
        TurnStatus: "queued" | "processing" | "completed" | "failed";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    liveness_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LivenessResponse"];
                };
            };
        };
    };
    readiness_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
            /** @description Alguma dependência está fora; o payload diz qual. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
        };
    };
    listar_sessoes_v1_sessions_get: {
        parameters: {
            query?: {
                /** @description Janela em dias. O que ficou fora dela não é erro, é ausência — a tela promete que o histórico longo vive na web. */
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    criar_sessao_v1_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
        };
    };
    encerrar_sessao_v1_sessions__session_id__end_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSummaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ler_cota_v1_students_me_quota_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuotaStatusResponse"];
                };
            };
        };
    };
    criar_turn_v1_sessions__session_id__turns_post: {
        parameters: {
            query?: never;
            header: {
                /** @description Chave gerada pelo cliente. Reenviar a mesma devolve o mesmo turn_id, sem criar nem reprocessar nada. */
                "Idempotency-Key": string;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_criar_turn_v1_sessions__session_id__turns_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnAcceptedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obter_turn_v1_turns__turn_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                turn_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    descartar_turn_v1_turns__turn_id__discard_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                turn_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    traduzir_texto_do_turn_v1_turns__turn_id__translations_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                turn_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TranslationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranslationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    acompanhar_turn_v1_turns__turn_id__events_get: {
        parameters: {
            query?: never;
            header?: {
                /** @description O `id:` do último evento recebido. O servidor reenvia só o que vem depois dele, lendo do banco (ADR-0026, item 3). */
                "Last-Event-ID"?: string | null;
            };
            path: {
                turn_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Fluxo `text/event-stream`. Cada evento carrega, em `data`, o payload do seu `event:` — o mapa é `TurnEventPayloads`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["TurnEventPayloads"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
