/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness — o processo responde */
        get: operations["liveness_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness — as dependências de infraestrutura respondem
         * @description 200 apenas se as três dependências responderem; 503 caso contrário.
         *
         *     O corpo é o mesmo nos dois casos — quem depura precisa saber *qual* caiu, e
         *     isso não deve depender de o endpoint ter respondido 200.
         */
        get: operations["readiness_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Abre uma sessão de conversa */
        post: operations["criar_sessao_v1_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{session_id}/turns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Envia a fala do aluno e enfileira o turno
         * @description ``202`` com o ``turn_id``. O trabalho começa depois da resposta.
         *
         *     O cabeçalho é **obrigatório** de propósito. Torná-lo opcional ("se faltar, eu
         *     gero uma") faria o esquecimento do cliente virar um turno extra processado e
         *     pago, em silêncio — e a rede móvel, que é o caso de uso inteiro da
         *     idempotência, é justamente onde o reenvio acontece.
         */
        post: operations["criar_turn_v1_sessions__session_id__turns_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/turns/{turn_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * O turno completo — o contrato de recuo (ADR-0026, item 4)
         * @description Tudo que o app precisa mostrar, com as URLs já assinadas.
         *
         *     Assinar N trechos são N HMACs locais (microssegundos cada, ADR-0024) — é o
         *     que torna aceitável entregar as URLs prontas em vez de o cliente pedir uma
         *     por trecho, que era o roundtrip por frase que o ADR-0024 recusou.
         */
        get: operations["obter_turn_v1_turns__turn_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/turns/{turn_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Entrega progressiva por SSE (ADR-0026)
         * @description O stream. Fecha em ``completed``/``failed``, no prazo, ou no disconnect.
         *
         *     **Quem fecha no disconnect é o `sse-starlette`**, e é o principal motivo de a
         *     biblioteca existir aqui: ele observa a mensagem ASGI ``http.disconnect`` e
         *     **cancela a corrotina** deste gerador. O cancelamento propaga para o
         *     ``async with`` da assinatura dentro do caso de uso, que desfaz o
         *     ``SUBSCRIBE`` e devolve a conexão do Redis. Sem isso, um aluno que fecha o
         *     app deixaria uma conexão pendurada até o prazo de 60 s — multiplicado por
         *     todo mundo.
         *
         *     O `Last-Event-ID` chega por cabeçalho porque é assim que o `EventSource`
         *     nativo reconecta: ele o manda sozinho, sem o cliente escrever uma linha.
         */
        get: operations["acompanhar_turn_v1_turns__turn_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_criar_turn_v1_sessions__session_id__turns_post */
        Body_criar_turn_v1_sessions__session_id__turns_post: {
            /**
             * Audio
             * @description A fala do aluno.
             */
            audio: string;
        };
        /**
         * ChunkPayload
         * @description Um trecho tocável da resposta — no GET e no evento ``chunk``.
         *
         *     ``url`` é uma URL **pré-assinada e de vida curta** (ADR-0024): ela é montada
         *     no momento da entrega, com TTL de ``media_url_ttl``. Não é endereço estável e
         *     não deve ser guardada pelo cliente além do playback do turn.
         */
        ChunkPayload: {
            /**
             * Index
             * @description 0-based e denso; é a ordem de playback.
             */
            index: number;
            /**
             * Url
             * @description URL assinada, válida por media_url_ttl.
             */
            url: string;
            /** Duration Seconds */
            duration_seconds: number;
            /**
             * Text
             * @description A frase que gerou este trecho.
             */
            text: string;
        };
        /**
         * CompletedPayload
         * @description Evento ``completed``. Carrega a URL do áudio inteiro, já assinada.
         */
        CompletedPayload: {
            /** Reply Audio Url */
            reply_audio_url: string;
        };
        /**
         * CorrectionPayload
         * @description Uma correção tipada — no ``GET`` e no evento ``feedback``.
         *
         *     Mesma garantia do ``ChunkPayload`` e pela mesma razão (ADR-0026): o payload
         *     do evento e o do ``GET`` descrevem a mesma coisa, então **saem do mesmo
         *     schema** ou divergem no primeiro campo que alguém acrescentar a um só.
         *
         *     ``index`` viaja porque ele não é detalhe de armazenamento: é a **ordem
         *     pedagógica**, e é o contrato que diz ao cliente qual correção destacar
         *     quando só couber uma na tela (CARD-016).
         */
        CorrectionPayload: {
            /**
             * Index
             * @description 0-based e denso; é a ordem pedagógica.
             */
            index: number;
            type: components["schemas"]["CorrectionType"];
            /**
             * Original Excerpt
             * @description Trecho verbatim da fala do aluno.
             */
            original_excerpt: string;
            /** Corrected Form */
            corrected_form: string;
            /** Explanation */
            explanation: string;
            /** @description Escala fechada. O rótulo em pt-BR é do cliente, não daqui. */
            severity: components["schemas"]["Severity"];
        };
        /**
         * CorrectionType
         * @description A natureza do erro. Enum **fechado**, como ``TurnStatus``.
         *
         *     Acrescentar um valor é aditivo e permitido; renomear não é (ADR-0008), e a
         *     consequência de renomear é dupla — quebra o cliente antigo **e** invalida
         *     todo valor já gravado na coluna, porque o Postgres guarda o texto do membro.
         *
         *     ``OTHER`` existe para que o modelo tenha para onde ir quando a correção não
         *     couber nas outras quatro. Sem essa saída, o custo de uma classificação
         *     impossível seria uma resposta fora do schema — ou seja, ``LlmError`` e turn
         *     falho por um erro de taxonomia.
         * @enum {string}
         */
        CorrectionType: "grammar" | "vocabulary" | "preposition" | "word_order" | "other";
        /**
         * DependencyCheck
         * @description Estado de uma dependência de infraestrutura.
         */
        DependencyCheck: {
            /**
             * Status
             * @enum {string}
             */
            status: "up" | "down";
            /** Latency Ms */
            latency_ms: number;
            /** Error */
            error?: string | null;
        };
        /**
         * FailedPayload
         * @description Evento ``failed`` — inclusive depois de entrega parcial (ADR-0023).
         */
        FailedPayload: {
            /** Reason */
            reason: string;
            /** Delivered Partially */
            delivered_partially: boolean;
        };
        /**
         * FeedbackPayload
         * @description Evento ``feedback`` — agora reconstruído na retomada (CARD-013).
         *
         *     Era **o único evento que a retomada não reconstruía**, porque correção não
         *     era persistida (ADR-0035, ADR-0041 item 5). Com ``turn.corrections`` no
         *     banco, o gatilho que aquele ADR deixou escrito disparou e ele volta como
         *     qualquer outro.
         *
         *     **Os quatro campos velhos continuam aqui, e continuam obrigatórios**
         *     (ADR-0008: proibido remover ou renomear dentro de ``/v1`` — a restrição dura
         *     é o app na loja que não atualiza quando queremos). O que mudou é de onde
         *     saem: eles são **derivados** de ``corrections`` por ``legacy_summary``, e não
         *     mais gerados pelo modelo. Quando morrem: no ``/v2``, ou antes, quando o app
         *     mínimo suportado já ler ``corrections[]``.
         */
        FeedbackPayload: {
            /**
             * Has Mistakes
             * @description LEGADO — derivado de corrections.
             */
            has_mistakes: boolean;
            /**
             * Original
             * @description LEGADO — corrections[0].original_excerpt.
             */
            original: string;
            /**
             * Corrected
             * @description LEGADO — corrections[0].corrected_form.
             */
            corrected: string;
            /**
             * Tip
             * @description LEGADO — corrections[0].explanation.
             */
            tip: string;
            /**
             * Corrections
             * @description Correções tipadas (CARD-013). Campo ADITIVO.
             */
            corrections?: components["schemas"]["CorrectionPayload"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LivenessResponse
         * @description Resposta de ``GET /health``.
         */
        LivenessResponse: {
            /**
             * Status
             * @default alive
             * @constant
             */
            status: "alive";
        };
        /**
         * ReadinessResponse
         * @description Resposta de ``GET /health/ready``.
         *
         *     ``status`` é redundante em relação a ``checks`` de propósito: quem faz
         *     probe lê só o código HTTP, quem depura lê o mapa inteiro.
         */
        ReadinessResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "not_ready";
            /** Checks */
            checks?: {
                [key: string]: components["schemas"]["DependencyCheck"];
            };
        };
        /**
         * SessionResponse
         * @description ``POST /v1/sessions`` — o mínimo para o cliente ter onde falar.
         */
        SessionResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Student Id
             * Format: uuid
             */
            student_id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Is Active */
            is_active: boolean;
        };
        /**
         * Severity
         * @description Quanto o erro pesa. Três níveis, e o número é a decisão.
         *
         *     A UI apresenta severidade em **palavras** ("pequeno ajuste", "vale revisar")
         *     — o que só é traduzível a partir de uma escala pequena e estável. Três é o
         *     menor número que ainda permite ordenar e destacar sem virar escala falsa;
         *     dois perderiam o meio-termo, e um quarto nível ("critical") seria um rótulo
         *     que nem o modelo nem o produto sabem definir num tutor de conversa, ainda
         *     mais sem eval (Fase 4).
         *
         *     **O rótulo em pt-BR não mora aqui.** Tradução é apresentação e vive no
         *     cliente (CARD-016): o dia em que a mesma correção precisar aparecer em duas
         *     línguas, o domínio não muda.
         * @enum {string}
         */
        Severity: "minor" | "moderate" | "major";
        /**
         * TranscribedPayload
         * @description Evento ``transcribed``.
         */
        TranscribedPayload: {
            /** Transcript */
            transcript: string;
        };
        /**
         * TurnAcceptedResponse
         * @description ``202`` do ``POST`` — o turn está aceito e a caminho.
         */
        TurnAcceptedResponse: {
            /**
             * Turn Id
             * Format: uuid
             */
            turn_id: string;
            /**
             * Replayed
             * @description true quando a Idempotency-Key já tinha sido usada: nenhum turn novo foi criado e nada é reprocessado.
             */
            replayed: boolean;
        };
        /**
         * TurnEventPayloads
         * @description **Não é resposta de rota nenhuma.** Existe para o OpenAPI enxergar o SSE.
         *
         *     O ADR-0008 promete que mudança de contrato quebra o cliente **em build**. Essa
         *     promessa era **falsa para quatro dos cinco eventos**: a rota do stream devolve
         *     ``EventSourceResponse``, que não é modelo pydantic, então os payloads nunca
         *     chegavam ao OpenAPI — e portanto nunca chegavam aos tipos gerados. Só
         *     ``ChunkPayload`` escapava, por carona em ``TurnResponse.chunks``.
         *
         *     Descoberto no CARD-012, ao escrever o primeiro consumidor. Este envelope é a
         *     correção mínima: declarado no ``responses`` da rota, ele arrasta os cinco para
         *     ``components.schemas``. Um campo renomeado em qualquer evento passa a virar
         *     ``error TS2339`` no app, que é o ponto inteiro do ADR-0008.
         *
         *     Os nomes dos campos são os cinco nomes de evento do ADR-0026 — de propósito:
         *     quem ler o tipo gerado descobre o mapa ``event: → payload`` sem sair dele.
         */
        TurnEventPayloads: {
            transcribed: components["schemas"]["TranscribedPayload"];
            chunk: components["schemas"]["ChunkPayload"];
            feedback: components["schemas"]["FeedbackPayload"];
            completed: components["schemas"]["CompletedPayload"];
            failed: components["schemas"]["FailedPayload"];
        };
        /**
         * TurnResponse
         * @description ``GET /v1/turns/{id}`` — completo e verdadeiro (ADR-0026, item 4).
         *
         *     Este é o **contrato de recuo**: um cliente que nunca abra o stream tem de
         *     conseguir levar um turn até o fim só com esta rota. É por isso que ela
         *     devolve tudo, e não um resumo.
         */
        TurnResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /** @description Estado grosso; não cresce (ADR-0008). */
            status: components["schemas"]["TurnStatus"];
            /** @description Etapa exibida, DERIVADA (ADR-0023/0028). */
            stage: components["schemas"]["TurnStage"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Transcript */
            transcript?: string | null;
            /** Reply Text */
            reply_text?: string | null;
            /**
             * Reply Audio Url
             * @description Áudio inteiro concatenado, assinado. Nulo antes de completar — ou depois de a retenção expirar (ADR-0024).
             */
            reply_audio_url?: string | null;
            /**
             * Delivered Partially
             * @description Falhou DEPOIS de o aluno já ter ouvido algo (ADR-0023).
             */
            delivered_partially: boolean;
            /** Failure Reason */
            failure_reason?: string | null;
            /**
             * Chunks
             * @description Campo ADITIVO (ADR-0008).
             */
            chunks?: components["schemas"]["ChunkPayload"][];
            /**
             * Corrections
             * @description Correções tipadas e persistidas (CARD-013). Campo ADITIVO.
             */
            corrections?: components["schemas"]["CorrectionPayload"][];
        };
        /**
         * TurnStage
         * @description Etapa exibida ao aluno — **derivada**, nunca persistida (ADR-0023).
         *
         *     O vocabulário é o mesmo do ADR-0016; o que mudou foi a ordem em que os
         *     artefatos aparecem. ``queued`` não está aqui de propósito: nenhuma tela
         *     distingue "na fila" de "transcrevendo", e expor isso vazaria mecânica de
         *     infraestrutura no contrato.
         * @enum {string}
         */
        TurnStage: "transcribing" | "thinking" | "speaking" | "completed";
        /**
         * TurnStatus
         * @description Estado de execução do Turn (ADR-0023).
         *
         *     ``StrEnum`` (Python 3.11+) é uma enum cujos membros **são** strings: o valor
         *     vai para o banco e para o JSON sem conversão manual, e ainda assim o mypy
         *     cobra o tipo. Em C# você precisaria de um conversor ou de um
         *     ``[JsonStringEnumConverter]`` para o mesmo efeito.
         *
         *     A enum **não ganha valor** com a cascata, e isso é deliberado: acrescentar
         *     ``speaking`` aqui quebraria o contrato aditivo do ADR-0008 (cliente antigo
         *     que trate os casos de forma exaustiva) e recriaria a duplicação que o
         *     ADR-0016 rejeitou. A granularidade fina vive em ``TurnStage``, que é
         *     derivado e por isso pode crescer sem migration.
         * @enum {string}
         */
        TurnStatus: "queued" | "processing" | "completed" | "failed";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    liveness_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LivenessResponse"];
                };
            };
        };
    };
    readiness_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
            /** @description Alguma dependência está fora; o payload diz qual. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
        };
    };
    criar_sessao_v1_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
        };
    };
    criar_turn_v1_sessions__session_id__turns_post: {
        parameters: {
            query?: never;
            header: {
                /** @description Chave gerada pelo cliente. Reenviar a mesma devolve o mesmo turn_id, sem criar nem reprocessar nada. */
                "Idempotency-Key": string;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_criar_turn_v1_sessions__session_id__turns_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnAcceptedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obter_turn_v1_turns__turn_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                turn_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    acompanhar_turn_v1_turns__turn_id__events_get: {
        parameters: {
            query?: never;
            header?: {
                /** @description O `id:` do último evento recebido. O servidor reenvia só o que vem depois dele, lendo do banco (ADR-0026, item 3). */
                "Last-Event-ID"?: string | null;
            };
            path: {
                turn_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Fluxo `text/event-stream`. Cada evento carrega, em `data`, o payload do seu `event:` — o mapa é `TurnEventPayloads`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["TurnEventPayloads"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
